Algoritmo "cont_1_10"
// Disciplina   : [Algoritmo]
// Professor   : Silvia Maria 
// Descrição   : contador de 1 ate 10
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/11/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  x := 1
  
enquanto (x <= 10) faca

   escreval(x)
   x := x + 1
   
fimenquanto

Fimalgoritmo