Algoritmo "contador_50_100"
// Disciplina   : [Algoritmo]
// Professor   : Silvia Maria 
// Descrição   :
//1. Faça um programa que escreva de 50 a 100.

// Autor(a)    : Jessica F. de Oliveira
// Data atual  : 18/11/2021
Var
// Seção de Declarações das variáveis 
cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Contando de 50 a 100")

para cont de 50 ate 100 faca

     escreval(cont)

fimpara

Fimalgoritmo