Algoritmo "cont_30_50_de_2_em_2"
// Disciplina   : [Algoritmo]
// Professor   : Silvia Maria 
// Descrição   :
//2.Faça um programa que escreva de 30 a 50 contandode 2 em 2.
// Autor(a)    : Jessica F. Oliveira
// Data atual  : 18/11/2021
Var
// Seção de Declarações das variáveis 
 cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para cont de 30 ate 50 passo 2 faça

     escreval(cont)
     
fimpara

Fimalgoritmo