Algoritmo "nome_usuario"
// Disciplina   : [Algoritmo]
// Professor   : Silvia Maria 
// Descrição   : 12) No VISUALG entre com um
//nome qualquer e o imprima.
// Autor(a)    : Jessica Francisca de OLiveira
// Data atual  : 08/10/2021
Var
// Seção de Declarações das variáveis 


nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite seu nome: ")
leia(nome)

escreval("")
escreval("Olá ", nome, ", bem vindo(a)!")


Fimalgoritmo