Algoritmo "eu_amo_TI_1"
// Disciplina   : [Algoritmo]
// Professor   : Silvia Maria 
// Descrição   :
//1)	Escrever um algoritmo que permita escrever
// dez vezes a frase "Eu amo TI!"

// Autor(a)    : Jessica F. de Oliveira
// Data atual  : 18/11/2021
Var
// Seção de Declarações das variáveis 

amoTI: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


para amoTI de 1 ate 10 faça

     escreval(amoTI, "° Eu amo TI!")
     
fimpara

Fimalgoritmo